# Generated by Django 3.1.3 on 2020-11-18 22:44

from django.db import migrations, models
import django.db.models.deletion
import wagtail_color_panel.fields
import wagtailmetadata.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('repeat_in_subnav', models.BooleanField(default=False, help_text="If checked, a link to this page will be repeated alongside it's direct children when displaying a sub-navigation for this page.", verbose_name='repeat in sub-navigation')),
                ('repeated_item_text', models.CharField(blank=True, help_text="e.g. 'Section home' or 'Overview'. If left blank, the page title will be used.", max_length=255, verbose_name='repeated item link text')),
                ('overlay_color', wagtail_color_panel.fields.ColorField(default='#000000', max_length=7, verbose_name='Overlay Color')),
                ('overlay_opacity', models.CharField(choices=[('0', '0%'), ('.1', '10%'), ('.2', '20%'), ('.3', '30%'), ('.4', '40%'), ('.5', '50%'), ('.6', '60%'), ('.7', '70%'), ('.8', '80%'), ('.9', '90%'), ('1', '100%')], default='.7', max_length=4, verbose_name='Overlay Opacity')),
                ('form', models.TextField(help_text='Place the entire Infusionsoft JavaScript snippet for the form here.', max_length=2000, null=True, verbose_name='Infusionsoft Embed Code')),
                ('map_link', models.CharField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3145.0021611401385!2d-120.3411954482222!3d37.977078879623534!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8090c5d17033cac3%3A0x74f095a97c40b694!2sPeak%20Performance%20Care!5e0!3m2!1sen!2sus!4v1605503238589!5m2!1sen!2sus', max_length=1000, null=True, verbose_name='Google Map Embed URL')),
                ('map_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Map Image')),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Search image')),
                ('title_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Contact Page',
            },
            bases=(wagtailmetadata.models.MetadataMixin, 'wagtailcore.page', models.Model),
        ),
    ]
