# Generated by Django 3.1.3 on 2020-11-19 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptservice',
            name='service_type',
        ),
    ]
