# Generated by Django 3.1.3 on 2020-11-19 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_ptservice_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellnessservice',
            name='service_type',
        ),
    ]
