# Generated by Django 3.1.3 on 2020-11-19 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('education', '0003_auto_20201119_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopasswordpage',
            name='content',
        ),
        migrations.AddField(
            model_name='videopasswordpage',
            name='video_thumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Video Thumbnail'),
        ),
        migrations.AddField(
            model_name='videopasswordpage',
            name='video_title',
            field=models.CharField(max_length=255, null=True, verbose_name='Video Title'),
        ),
        migrations.AddField(
            model_name='videopasswordpage',
            name='youtube_link',
            field=models.URLField(null=True, verbose_name='YouTube Link'),
        ),
    ]
