# Generated by Django 3.1.3 on 2020-11-19 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20201119_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopasswordpage',
            name='video_title',
        ),
    ]
