# Generated by Django 3.1.3 on 2020-11-19 20:40

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_auto_20201119_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videopasswordpage',
            old_name='categories',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='videotag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_tags', to='education.videopasswordpage'),
        ),
    ]
