# Generated by Django 3.1.3 on 2020-11-19 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_auto_20201119_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videospasswordpage',
            name='content',
        ),
    ]
